/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import University.CourseSchedule.CourseLoad;
import University.CourseSchedule.SeatAssignment;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HU
 */
public class StudentViewTranscriptJPanel extends javax.swing.JPanel {
    private Business business;
    private StudentProfile studentProfile;
    private JPanel CardSequencePanel;
    /**
     * Creates new form StudentViewTranscriptJPanel
     */
    public StudentViewTranscriptJPanel(Business business, StudentProfile studentProfile, JPanel CardSequencePanel) {
        initComponents();
        this.business = business;
        this.studentProfile = studentProfile;
        this.CardSequencePanel = CardSequencePanel;
        populateTranscriptTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyTranscript = new javax.swing.JTable();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 155, 155));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("My Transcript");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Transcript");

        tblMyTranscript.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Course Faculty", "Course GPA"
            }
        ));
        jScrollPane1.setViewportView(tblMyTranscript);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Back)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        // Directly switch back to the FacultyWorkAreaJPanel
        CardSequencePanel.remove(this);
        StudentWorkAreaJPanel studentWorkAreaJPanel = new StudentWorkAreaJPanel(business, studentProfile, CardSequencePanel);
        CardSequencePanel.add(studentWorkAreaJPanel);
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed
        private void populateTranscriptTable() {
            DefaultTableModel model = (DefaultTableModel) tblMyTranscript.getModel();
            model.setRowCount(0);

            CourseLoad currentCourseLoad = studentProfile.getCurrentCourseLoad();
            if (currentCourseLoad != null) {
                for (SeatAssignment seatAssignment : currentCourseLoad.getSeatAssignments()) {
                    Object[] row = new Object[4];
                    row[0] = seatAssignment.getAssociatedCourse().getCourseNumber();
                    row[1] = seatAssignment.getAssociatedCourse().getCourseName();
                    row[2] = seatAssignment.getCourseOffer().getFacultyProfile().getName();
                    row[3] = seatAssignment.getGrade();
                    model.addRow(row);
                }
            }
        }

        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMyTranscript;
    // End of variables declaration//GEN-END:variables
}
