/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.HomeAddressDirectory;
import model.BankAccountDirectory;
import model.PersonDirectory;
import model.Person;
import model.LocalAddressDirectory;

/**
 *
 * @author HU
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    HomeAddressDirectory homeAddressList;
    LocalAddressDirectory localAddressList;
    BankAccountDirectory bankAccountList;
    PersonDirectory personList;
    
    
    public MainJFrame() {
        initComponents();
        
        homeAddressList = new HomeAddressDirectory();
        localAddressList = new LocalAddressDirectory();
        bankAccountList = new BankAccountDirectory();        
        personList = new PersonDirectory();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        btnCreateHomeAdd = new javax.swing.JButton();
        btnViewHomeAdd = new javax.swing.JButton();
        btnCreateLocalAdd = new javax.swing.JButton();
        btnViewLocalAdd = new javax.swing.JButton();
        btnCreateBankAcc = new javax.swing.JButton();
        btnViewBankAcc = new javax.swing.JButton();
        workPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnViewPerson.setText("View Person");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnCreateHomeAdd.setText("Create Home Address");
        btnCreateHomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHomeAddActionPerformed(evt);
            }
        });

        btnViewHomeAdd.setText("View Home Address");
        btnViewHomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHomeAddActionPerformed(evt);
            }
        });

        btnCreateLocalAdd.setText("Create Local Address");
        btnCreateLocalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLocalAddActionPerformed(evt);
            }
        });

        btnViewLocalAdd.setText("View Local Address");
        btnViewLocalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocalAddActionPerformed(evt);
            }
        });

        btnCreateBankAcc.setText("Create Bank Account");
        btnCreateBankAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBankAccActionPerformed(evt);
            }
        });

        btnViewBankAcc.setText("View Bank Account");
        btnViewBankAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBankAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateHomeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewHomeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewLocalAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewBankAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateBankAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateLocalAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(btnCreatePerson)
                .addGap(18, 18, 18)
                .addComponent(btnViewPerson)
                .addGap(101, 101, 101)
                .addComponent(btnCreateHomeAdd)
                .addGap(18, 18, 18)
                .addComponent(btnViewHomeAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnCreateLocalAdd)
                .addGap(18, 18, 18)
                .addComponent(btnViewLocalAdd)
                .addGap(97, 97, 97)
                .addComponent(btnCreateBankAcc)
                .addGap(18, 18, 18)
                .addComponent(btnViewBankAcc)
                .addGap(76, 76, 76))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateBankAcc, btnCreateHomeAdd, btnCreateLocalAdd, btnCreatePerson, btnViewBankAcc, btnViewHomeAdd, btnViewLocalAdd, btnViewPerson});

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
               ViewPersonJPanel viewPersonPanel = new ViewPersonJPanel(personList);
               splitPane.setRightComponent(viewPersonPanel);
        
        
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
           CreatePersonJPanel createPersonPanel = new CreatePersonJPanel(personList);
           splitPane.setRightComponent(createPersonPanel);
           
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnCreateHomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHomeAddActionPerformed
        // TODO add your handling code here:
           CreateHomeAddressJPanel createHomeAddressPanel = new CreateHomeAddressJPanel(homeAddressList);
           splitPane.setRightComponent(createHomeAddressPanel);
        
    }//GEN-LAST:event_btnCreateHomeAddActionPerformed

    private void btnViewHomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHomeAddActionPerformed
        // TODO add your handling code here:
                ViewHomeAddressJPanel viewHomeAddressPanel = new ViewHomeAddressJPanel(homeAddressList);
               splitPane.setRightComponent(viewHomeAddressPanel);
        
    }//GEN-LAST:event_btnViewHomeAddActionPerformed

    private void btnCreateLocalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLocalAddActionPerformed
        // TODO add your handling code here:
            CreateLocalAddressJPanel createLocalAddressPanel = new CreateLocalAddressJPanel(localAddressList);
           splitPane.setRightComponent(createLocalAddressPanel);       
        
    }//GEN-LAST:event_btnCreateLocalAddActionPerformed

    private void btnViewLocalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocalAddActionPerformed
        // TODO add your handling code here:
        
               ViewLocalAddressJPanel viewLocalAddressPanel = new ViewLocalAddressJPanel(localAddressList);
               splitPane.setRightComponent(viewLocalAddressPanel);
    }//GEN-LAST:event_btnViewLocalAddActionPerformed

    private void btnCreateBankAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBankAccActionPerformed
        // TODO add your handling code here:
           CreateBankAccountJPanel createBankAccountPanel = new CreateBankAccountJPanel(bankAccountList);
           splitPane.setRightComponent(createBankAccountPanel);       
        
    }//GEN-LAST:event_btnCreateBankAccActionPerformed

    private void btnViewBankAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBankAccActionPerformed
        // TODO add your handling code here:
            ViewBankAccountJPanel viewBankAccountPanel = new ViewBankAccountJPanel(bankAccountList);
            splitPane.setRightComponent(viewBankAccountPanel);        
        
    }//GEN-LAST:event_btnViewBankAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBankAcc;
    private javax.swing.JButton btnCreateHomeAdd;
    private javax.swing.JButton btnCreateLocalAdd;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnViewBankAcc;
    private javax.swing.JButton btnViewHomeAdd;
    private javax.swing.JButton btnViewLocalAdd;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
