/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import University.Department.*;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import javax.swing.JPanel;
import UserInterface.WorkAreas.FacultyRole.ManageCourseScheduleJPanel;

/**
 *
 * @author kal
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;


    /**
     * Creates new form UnitRiskWorkArea
     */

    public FacultyWorkAreaJPanel(Business b, JPanel clp) {
        business = b;
        this.CardSequencePanel = clp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnManageCourse = new javax.swing.JButton();
        jbtnPerformanceReports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCourseSchedule = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        jbtnManageCourse.setBackground(new java.awt.Color(102, 153, 255));
        jbtnManageCourse.setFont(getFont());
        jbtnManageCourse.setForeground(new java.awt.Color(255, 255, 255));
        jbtnManageCourse.setText(" Manage Courses");
        jbtnManageCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnManageCourse.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtnManageCourse.setMinimumSize(new java.awt.Dimension(20, 23));
        jbtnManageCourse.setPreferredSize(new java.awt.Dimension(240, 30));
        jbtnManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnManageCourseIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        jbtnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        jbtnPerformanceReports.setFont(getFont());
        jbtnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPerformanceReports.setText("Performance Reports");
        jbtnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        jbtnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        jbtnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        jbtnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPerformanceReportsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Faculty Profie");

        btnCourseSchedule.setBackground(new java.awt.Color(102, 153, 255));
        btnCourseSchedule.setFont(getFont());
        btnCourseSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseSchedule.setText("Course Schedules");
        btnCourseSchedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseSchedule.setMaximumSize(new java.awt.Dimension(145, 40));
        btnCourseSchedule.setMinimumSize(new java.awt.Dimension(20, 20));
        btnCourseSchedule.setPreferredSize(new java.awt.Dimension(240, 25));
        btnCourseSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseScheduleIdentifyEventsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCourseSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(jbtnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(636, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnCourseSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnManageCourseIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnManageCourseIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        ManageCourseJPanel manageCourseJPanel = new ManageCourseJPanel(business, CardSequencePanel);

        CardSequencePanel.add("Manage Courses", manageCourseJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_jbtnManageCourseIdentifyResourceAssetsActionPerformed

    private void jbtnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPerformanceReportsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        FacultyStudentsReportsJPanel facultyStudentsReportsJPanel = new FacultyStudentsReportsJPanel(business, "Spring2024", CardSequencePanel);

        CardSequencePanel.add("Manage Courses", facultyStudentsReportsJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        

}//GEN-LAST:event_jbtnPerformanceReportsActionPerformed

    private void btnCourseScheduleIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseScheduleIdentifyEventsActionPerformed
        // TODO add your handling code here:
            // Remove the current panel from the CardSequencePanel
        CardSequencePanel.removeAll();

        // Create a new instance of ManageCourseScheduleJPanel
        ManageCourseScheduleJPanel manageCourseScheduleJPanel = new ManageCourseScheduleJPanel(business, CardSequencePanel);

        // Add the ManageCourseScheduleJPanel to the CardSequencePanel
        CardSequencePanel.add("Manage Course Schedule", manageCourseScheduleJPanel);

        // Refresh the CardSequencePanel
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();

        // Navigate to the ManageCourseScheduleJPanel
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
    }//GEN-LAST:event_btnCourseScheduleIdentifyEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseSchedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnManageCourse;
    private javax.swing.JButton jbtnPerformanceReports;
    // End of variables declaration//GEN-END:variables

}
