/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.*;
import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import University.CourseCatalog.Course;
import University.CourseCatalog.CourseCatalog;
import University.Department.*;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HU
 */
public class ManageCourseJPanel extends javax.swing.JPanel {
    JPanel CardSequencePanel;
    public Business business;
    public Department department;
    public UserAccount selecteduseraccount;
    /**
     * Creates new form ManageCourse1JPanel
     */
    public ManageCourseJPanel(Business bz, JPanel jp) {
        initComponents();
        CardSequencePanel = jp;
        this.business = bz;
        refreshTable();
    }
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jtblCourseCatalog.getModel();
        model.setRowCount(0); // Clear existing rows

        // Retrieve the department from the business object
        Department department = retrieveDepartmentFromBusiness(business);
        if (department != null) {
            CourseCatalog courseCatalog = department.getCourseCatalog();
            for (Course course : courseCatalog.getCourseList()) {
                Object[] row = new Object[4];
                row[0] = course;
                row[1] = course.getCourseName();
                row[2] = course.getCredits();
                row[3] = course.getCoursePrice();
                model.addRow(row);
            }
        }
    }
    
        private Department retrieveDepartmentFromBusiness(Business business) {
        // Logic to retrieve the appropriate department from the business object
       
        String departmentName = "Information Systems"; 
        for (Department department : business.getDepartments()) {
            if (department.getName().equals(departmentName)) {
                return department;
            }
        }
        return null; // Return null if the department is not found
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCourseCatalog = new javax.swing.JTable();
        btnAddCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Courses");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CourseCatalog");

        jtblCourseCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Credits", "Price (USD)"
            }
        ));
        jScrollPane1.setViewportView(jtblCourseCatalog);

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setText("Delete Course");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(btnDeleteCourse)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Back)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    // Directly switch back to the FacultyWorkAreaJPanel
    CardSequencePanel.remove(this); // Remove the current panel
    FacultyWorkAreaJPanel facultyPanel = new FacultyWorkAreaJPanel(business, CardSequencePanel);
    CardSequencePanel.add(facultyPanel); // Add the faculty panel back to the CardSequencePanel
    CardSequencePanel.revalidate();
    CardSequencePanel.repaint();
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
            CardSequencePanel.removeAll();

    AddCourseJPanel addCourseJPanel = new AddCourseJPanel(business, CardSequencePanel);

    CardSequencePanel.add("Add Course", addCourseJPanel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
        
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
                int selectedRow = jtblCourseCatalog.getSelectedRow();
        if (selectedRow == -1) {
            // No row is selected, display an error message
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course to delete.");
            return;
        }

        // Retrieve the selected course from the table model
        Course selectedCourse = (Course) jtblCourseCatalog.getValueAt(selectedRow, 0);

        // Retrieve the department from the business object
        Department department = retrieveDepartmentFromBusiness(business);
        if (department != null) {
            CourseCatalog courseCatalog = department.getCourseCatalog();

            // Remove the selected course from the course catalog
            courseCatalog.removeCourse(selectedCourse);

            // Refresh the table to reflect the changes
            refreshTable();

            // Display a success message
            javax.swing.JOptionPane.showMessageDialog(this, "Course deleted successfully.");
        }
        
        
    }//GEN-LAST:event_btnDeleteCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblCourseCatalog;
    // End of variables declaration//GEN-END:variables
}
