/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import University.CourseSchedule.CourseSchedule;
import University.Department.Department;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HU
 */
public class ManageCourseScheduleJPanel extends javax.swing.JPanel {
    private JPanel CardSequencePanel;
    private Business business;
    /**
     * Creates new form ManageCourseScheduleJPanel
     */
    public ManageCourseScheduleJPanel(Business business, JPanel cardSequencePanel) {
        initComponents();
        this.business = business;
        this.CardSequencePanel = cardSequencePanel;
        refreshTable();
    }
    
    
    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourseSchedule.getModel();
        model.setRowCount(0);

        Department department = retrieveDepartmentFromBusiness(business);
        if (department != null) {
            for (String semester : department.mastercoursecatalog.keySet()) {
                Object[] row = new Object[]{semester};
                model.addRow(row);
            }
        }
    }
    
        private Department retrieveDepartmentFromBusiness(Business business) {
        String departmentName = "Information Systems";
        for (Department department : business.getDepartments()) {
            if (department.getName().equals(departmentName)) {
                return department;
            }
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseSchedule = new javax.swing.JTable();
        btnViewCourseOffer = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Course Schedule");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CourseSchedule");

        tblCourseSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Semester"
            }
        ));
        jScrollPane1.setViewportView(tblCourseSchedule);

        btnViewCourseOffer.setText("View Course Offers");
        btnViewCourseOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseOfferActionPerformed(evt);
            }
        });

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewCourseOffer)
                        .addGap(68, 68, 68)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCourseOffer)
                    .addComponent(Back))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCourseOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseOfferActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCourseSchedule.getSelectedRow();
        if (selectedRow >= 0) {
            String selectedSemester = (String) tblCourseSchedule.getValueAt(selectedRow, 0);
            Spring2024CourseOffersJPanel courseOffersJPanel = new Spring2024CourseOffersJPanel(business, selectedSemester, CardSequencePanel);
            CardSequencePanel.add(courseOffersJPanel);
            CardSequencePanel.revalidate();
            CardSequencePanel.repaint();
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        } else {
            // Show a notification when no row is selected
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course schedule.");
        }
    }//GEN-LAST:event_btnViewCourseOfferActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        // Directly switch back to the FacultyWorkAreaJPanel
        CardSequencePanel.remove(this);
        FacultyWorkAreaJPanel facultyPanel = new FacultyWorkAreaJPanel(business, CardSequencePanel);
        CardSequencePanel.add(facultyPanel);
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnViewCourseOffer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourseSchedule;
    // End of variables declaration//GEN-END:variables
}
