/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import University.CourseSchedule.CourseOffer;
import University.CourseSchedule.CourseSchedule;
import University.Department.Department;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HU
 */
public class Spring2024CourseOffersJPanel extends javax.swing.JPanel {

    public Business business;
    public String selectedSemester;
    public JPanel CardSequencePanel;

    /**
     * Creates new form Spring2024COurseOffersJPanel1
     */

    public Spring2024CourseOffersJPanel(Business business, String selectedSemester, JPanel CardSequencePanel) {
        initComponents();
        this.business = business;
        this.selectedSemester = selectedSemester;
        this.CardSequencePanel = CardSequencePanel;
        //Populate the course offers table for the selected semester
        populateCourseOffersTable();
    }
       
    private void populateCourseOffersTable() {
    // Retrieve the course schedule for the selected semester
    CourseSchedule courseSchedule = retrieveCourseSchedule(selectedSemester);
    if (courseSchedule != null) {
        // Retrieve the course offers for the selected semester
        ArrayList<CourseOffer> courseOffers = courseSchedule.getSchedule();
        // Populate the table with course offers
        DefaultTableModel model = (DefaultTableModel) tblCourseOffers.getModel();
        model.setRowCount(0);
        for (CourseOffer offer : courseOffers) {
            Object[] row = new Object[]{
                offer.getCourseNumber(),
                offer.getCourseName(),
                offer.getRemainingSeats(),
                offer.getTotalSeats(),
                offer.getFacultyProfile() != null ? offer.getFacultyProfile().getName() : "Not Assigned"
            };
            model.addRow(row);
        }
    }
}
    
    private CourseSchedule retrieveCourseSchedule(String semester) {
    Department department = retrieveDepartmentFromBusiness(business);
    if (department != null) {
        return department.getCourseSchedule(semester);
    }
    return null;
}
 private Department retrieveDepartmentFromBusiness(Business business) {
    String departmentName = "Information Systems";
    for (Department department : business.getDepartments()) {
        if (department.getName().equals(departmentName)) {
            return department;
        }
    }
    return null;
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseOffers = new javax.swing.JTable();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Course Schedule");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CourseOffering");

        tblCourseOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Seat Available", "Total Seat", "Faculty Name"
            }
        ));
        jScrollPane1.setViewportView(tblCourseOffers);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        // Directly switch back to the FacultyWorkAreaJPanel
        CardSequencePanel.remove(this);
        FacultyWorkAreaJPanel facultyPanel = new FacultyWorkAreaJPanel(business, CardSequencePanel);
        CardSequencePanel.add(facultyPanel);
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourseOffers;
    // End of variables declaration//GEN-END:variables
}
