/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole;

import UserInterface.WorkAreas.FacultyRole.*;
import Business.Business;
import University.CourseCatalog.Course;
import University.CourseCatalog.CourseCatalog;
import University.CourseSchedule.CourseOffer;
import University.CourseSchedule.CourseSchedule;
import University.Department.Department;
import University.Faculty.FacultyDirectory;
import University.Faculty.FacultyProfile;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HU
 */
public class AdminCourseOffersJPanel extends javax.swing.JPanel {

    public Business business;
    public String selectedSemester;
    public JPanel CardSequencePanel;

    /**
     * Creates new form Spring2024COurseOffersJPanel1
     */

    public AdminCourseOffersJPanel(Business business, String selectedSemester, JPanel CardSequencePanel) {
        initComponents();
        this.business = business;
        this.selectedSemester = selectedSemester;
        this.CardSequencePanel = CardSequencePanel;
        //Populate the course offers table for the selected semester
        populateCourseOffersTable();
        refrshCourseCatalogTable();
    }
       
    private void populateCourseOffersTable() {
    // Retrieve the course schedule for the selected semester
    CourseSchedule courseSchedule = retrieveCourseSchedule(selectedSemester);
    if (courseSchedule != null) {
        // Retrieve the course offers for the selected semester
        ArrayList<CourseOffer> courseOffers = courseSchedule.getSchedule();
        // Populate the table with course offers
        DefaultTableModel model = (DefaultTableModel) tblCourseOffers.getModel();
        model.setRowCount(0);
        for (CourseOffer offer : courseOffers) {
            Object[] row = new Object[]{
                offer.getCourseNumber(),
                offer.getCourseName(),
                offer.getRemainingSeats(),
                offer.getTotalSeats(),
                offer.getFacultyProfile() != null ? offer.getFacultyProfile().getName() : "Not Assigned"
            };
            model.addRow(row);
        }
    }
}

        public void refrshCourseCatalogTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourseCatalog.getModel();
        model.setRowCount(0); // Clear existing rows

        // Retrieve the department from the business object
        Department department = retrieveDepartmentFromBusiness(business);
        if (department != null) {
            CourseCatalog courseCatalog = department.getCourseCatalog();
            for (Course course : courseCatalog.getCourseList()) {
                Object[] row = new Object[4];
                row[0] = course;
                row[1] = course.getCourseName();
                row[2] = course.getCredits();
                row[3] = course.getCoursePrice();
                model.addRow(row);
            }
        }
    }
    
    private CourseSchedule retrieveCourseSchedule(String semester) {
    Department department = retrieveDepartmentFromBusiness(business);
    if (department != null) {
        return department.getCourseSchedule(semester);
    }
    return null;
}
 private Department retrieveDepartmentFromBusiness(Business business) {
    String departmentName = "Information Systems";
    for (Department department : business.getDepartments()) {
        if (department.getName().equals(departmentName)) {
            return department;
        }
    }
    return null;
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseOffers = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        btnAddCourseOffer = new javax.swing.JButton();
        txtTotalSeat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseCatalog = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAssignTeacher = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Admin Manage Course Offerings");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CourseOffering");

        tblCourseOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Seat Available", "Total Seat", "Faculty Name"
            }
        ));
        jScrollPane1.setViewportView(tblCourseOffers);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        btnAddCourseOffer.setText("Add CourseOffer");
        btnAddCourseOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseOfferActionPerformed(evt);
            }
        });

        txtTotalSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalSeatActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total Seat of Course:");

        tblCourseCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Credits", "Price (USD)"
            }
        ));
        jScrollPane2.setViewportView(tblCourseCatalog);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("CourseCatalog");

        btnAssignTeacher.setText("Assign Teacher");
        btnAssignTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAssignTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotalSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(274, 274, 274)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAddCourseOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(btnAddCourseOffer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(btnAssignTeacher))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        // Navigate back to the AdminCourseScheduleJPanel
        CardSequencePanel.remove(this);
        AdminCourseScheduleJPanel adminCourseSchedulePanel = new AdminCourseScheduleJPanel(business, CardSequencePanel);
        CardSequencePanel.add(adminCourseSchedulePanel);
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void txtTotalSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalSeatActionPerformed

    private void btnAddCourseOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseOfferActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCourseCatalog.getSelectedRow();
        if (selectedRow >= 0) {
            Course selectedCourse = (Course) tblCourseCatalog.getValueAt(selectedRow, 0);
            String courseNumber = selectedCourse.getCourseNumber();
            String totalSeatsStr = txtTotalSeat.getText();

            if (!totalSeatsStr.isEmpty()) {
                try {
                    int totalSeats = Integer.parseInt(totalSeatsStr);

                    Department department = retrieveDepartmentFromBusiness(business);
                    if (department != null) {
                        CourseSchedule courseSchedule = department.getCourseSchedule(selectedSemester);
                        if (courseSchedule != null) {
                            CourseOffer newCourseOffer = courseSchedule.newCourseOffer(courseNumber);
                            newCourseOffer.generateSeats(totalSeats);
                            populateCourseOffersTable();
                            txtTotalSeat.setText("");
                        }
                    }
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid total seats value. Please enter a valid number.");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter the total seats for the course offer.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a course from the course catalog.");
        }

        
    }//GEN-LAST:event_btnAddCourseOfferActionPerformed

    private void btnAssignTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTeacherActionPerformed
        // TODO add your handling code here:
            AdminAssignTeacherJPanel adminAssignTeacherPanel = new AdminAssignTeacherJPanel(business, selectedSemester, CardSequencePanel);
        CardSequencePanel.add(adminAssignTeacherPanel);
        CardSequencePanel.revalidate();
        CardSequencePanel.repaint();
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnAssignTeacherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnAddCourseOffer;
    private javax.swing.JButton btnAssignTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCourseCatalog;
    private javax.swing.JTable tblCourseOffers;
    private javax.swing.JTextField txtTotalSeat;
    // End of variables declaration//GEN-END:variables
}
