/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;

import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public AdminRoleWorkAreaJPanel(Business b, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUserAccounts = new javax.swing.JButton();
        btnStudentsReports = new javax.swing.JButton();
        btnManageCourseSchedule = new javax.swing.JButton();
        btnManageStudents = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnUserAccounts.setBackground(new java.awt.Color(102, 153, 255));
        btnUserAccounts.setFont(getFont());
        btnUserAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnUserAccounts.setText("Administer User Accounts");
        btnUserAccounts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUserAccounts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnUserAccounts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnUserAccounts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnStudentsReports.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentsReports.setFont(getFont());
        btnStudentsReports.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentsReports.setText("Student Reports");
        btnStudentsReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentsReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentsReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentsReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentsReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsReportsActionPerformed(evt);
            }
        });

        btnManageCourseSchedule.setBackground(new java.awt.Color(102, 153, 255));
        btnManageCourseSchedule.setFont(getFont());
        btnManageCourseSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourseSchedule.setText("Manage Course Schedule");
        btnManageCourseSchedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCourseSchedule.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageCourseSchedule.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageCourseSchedule.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageCourseSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseScheduleActionPerformed(evt);
            }
        });

        btnManageStudents.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudents.setFont(getFont());
        btnManageStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudents.setText("Manage Students");
        btnManageStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudents.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudents.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudents.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudentsReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageCourseSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCourseSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentsReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccountsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnUserAccountsIdentifyResourceAssetsActionPerformed

    private void btnManageCourseScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseScheduleActionPerformed
        // TODO add your handling code here:
        AdminCourseScheduleJPanel adminCourseScheduleJPanel = new AdminCourseScheduleJPanel(business, CardSequencePanel);
        CardSequencePanel.add("AdminCourseSchedule", adminCourseScheduleJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageCourseScheduleActionPerformed

    private void btnManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentsActionPerformed
        // TODO add your handling code here:
    AdminMngStudentCourseOffer adminMngStudentCourseOffer = new AdminMngStudentCourseOffer(business, "Spring2024", CardSequencePanel);
    CardSequencePanel.add("AdminMngStudentCourseOffer", adminMngStudentCourseOffer);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageStudentsActionPerformed

    private void btnStudentsReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsReportsActionPerformed
    // Create an instance of StudentsReportsJPanel and pass the required parameters
    StudentsReportsJPanel studentsReportsJPanel = new StudentsReportsJPanel(business, "Spring2024", CardSequencePanel);
    
    // Add the StudentsReportsJPanel to the CardSequencePanel
    CardSequencePanel.add("StudentsReportsJPanel", studentsReportsJPanel);
    
    // Navigate to the StudentsReportsJPanel
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnStudentsReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourseSchedule;
    private javax.swing.JButton btnManageStudents;
    private javax.swing.JButton btnStudentsReports;
    private javax.swing.JButton btnUserAccounts;
    // End of variables declaration//GEN-END:variables

}
